/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICollateralVault__factory } from "./ICollateralVault__factory";
export { ILoanCore__factory } from "./ILoanCore__factory";
