/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ILoanCore, ILoanCoreInterface } from "../ILoanCore";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "activateLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "calculateTotalOwed",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "interestRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "termDays",
        type: "uint256",
      },
    ],
    name: "createLoan",
    outputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
    ],
    name: "getBorrowerLoans",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "getLoan",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "loanId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "borrower",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "interestRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "termDays",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "dueDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountRepaid",
            type: "uint256",
          },
          {
            internalType: "enum ILoanCore.LoanStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct ILoanCore.Loan",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "isOverdue",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "markDefaulted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
    ],
    name: "repay",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ILoanCore__factory {
  static readonly abi = _abi;
  static createInterface(): ILoanCoreInterface {
    return new Interface(_abi) as ILoanCoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILoanCore {
    return new Contract(address, _abi, runner) as unknown as ILoanCore;
  }
}
