/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ILoanCore {
  export type LoanStruct = {
    loanId: BytesLike;
    borrower: AddressLike;
    amount: BigNumberish;
    interestRate: BigNumberish;
    termDays: BigNumberish;
    createdAt: BigNumberish;
    dueDate: BigNumberish;
    amountRepaid: BigNumberish;
    status: BigNumberish;
  };

  export type LoanStructOutput = [
    loanId: string,
    borrower: string,
    amount: bigint,
    interestRate: bigint,
    termDays: bigint,
    createdAt: bigint,
    dueDate: bigint,
    amountRepaid: bigint,
    status: bigint
  ] & {
    loanId: string;
    borrower: string;
    amount: bigint;
    interestRate: bigint;
    termDays: bigint;
    createdAt: bigint;
    dueDate: bigint;
    amountRepaid: bigint;
    status: bigint;
  };
}

export interface ILoanCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateLoan"
      | "calculateTotalOwed"
      | "createLoan"
      | "getBorrowerLoans"
      | "getLoan"
      | "isOverdue"
      | "liquidate"
      | "markDefaulted"
      | "repay"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateLoan",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTotalOwed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getLoan", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isOverdue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markDefaulted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "activateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTotalOwed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOverdue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
}

export interface ILoanCore extends BaseContract {
  connect(runner?: ContractRunner | null): ILoanCore;
  waitForDeployment(): Promise<this>;

  interface: ILoanCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateLoan: TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;

  calculateTotalOwed: TypedContractMethod<
    [loanId: BytesLike],
    [bigint],
    "view"
  >;

  createLoan: TypedContractMethod<
    [amount: BigNumberish, interestRate: BigNumberish, termDays: BigNumberish],
    [string],
    "nonpayable"
  >;

  getBorrowerLoans: TypedContractMethod<
    [borrower: AddressLike],
    [string[]],
    "view"
  >;

  getLoan: TypedContractMethod<
    [loanId: BytesLike],
    [ILoanCore.LoanStructOutput],
    "view"
  >;

  isOverdue: TypedContractMethod<[loanId: BytesLike], [boolean], "view">;

  liquidate: TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;

  markDefaulted: TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;

  repay: TypedContractMethod<[loanId: BytesLike], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateLoan"
  ): TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateTotalOwed"
  ): TypedContractMethod<[loanId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [amount: BigNumberish, interestRate: BigNumberish, termDays: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[borrower: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BytesLike],
    [ILoanCore.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOverdue"
  ): TypedContractMethod<[loanId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markDefaulted"
  ): TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[loanId: BytesLike], [void], "payable">;

  filters: {};
}
