/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CreditScoreVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREDIT_ASSESSMENT_TYPEHASH"
      | "LOAN_PROPOSAL_TYPEHASH"
      | "RISK_PARAMETERS_TYPEHASH"
      | "eip712Domain"
      | "getNonce"
      | "nonces"
      | "setTrustedSigner"
      | "trustedSigner"
      | "verifyCreditAssessment"
      | "verifyLoanProposal"
      | "verifyRiskParameters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreditAssessmentVerified"
      | "EIP712DomainChanged"
      | "LoanProposalVerified"
      | "TrustedSignerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREDIT_ASSESSMENT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOAN_PROPOSAL_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_PARAMETERS_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setTrustedSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCreditAssessment",
    values: [AddressLike, BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLoanProposal",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRiskParameters",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREDIT_ASSESSMENT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOAN_PROPOSAL_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_PARAMETERS_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCreditAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyLoanProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRiskParameters",
    data: BytesLike
  ): Result;
}

export namespace CreditAssessmentVerifiedEvent {
  export type InputTuple = [
    user: AddressLike,
    creditScore: BigNumberish,
    riskTier: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    creditScore: bigint,
    riskTier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    creditScore: bigint;
    riskTier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanProposalVerifiedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    loanAmount: BigNumberish,
    collateralAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    loanAmount: bigint,
    collateralAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    borrower: string;
    loanAmount: bigint;
    collateralAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedSignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreditScoreVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): CreditScoreVerifier;
  waitForDeployment(): Promise<this>;

  interface: CreditScoreVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREDIT_ASSESSMENT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  LOAN_PROPOSAL_TYPEHASH: TypedContractMethod<[], [string], "view">;

  RISK_PARAMETERS_TYPEHASH: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getNonce: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setTrustedSigner: TypedContractMethod<
    [_newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedSigner: TypedContractMethod<[], [string], "view">;

  verifyCreditAssessment: TypedContractMethod<
    [
      user: AddressLike,
      creditScore: BigNumberish,
      riskTier: string,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  verifyLoanProposal: TypedContractMethod<
    [
      borrower: AddressLike,
      loanAmount: BigNumberish,
      collateralAmount: BigNumberish,
      interestRate: BigNumberish,
      duration: BigNumberish,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  verifyRiskParameters: TypedContractMethod<
    [
      user: AddressLike,
      anomalyScore: BigNumberish,
      defaultProbability: BigNumberish,
      recoveryRate: BigNumberish,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREDIT_ASSESSMENT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LOAN_PROPOSAL_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_PARAMETERS_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setTrustedSigner"
  ): TypedContractMethod<[_newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyCreditAssessment"
  ): TypedContractMethod<
    [
      user: AddressLike,
      creditScore: BigNumberish,
      riskTier: string,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyLoanProposal"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      loanAmount: BigNumberish,
      collateralAmount: BigNumberish,
      interestRate: BigNumberish,
      duration: BigNumberish,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyRiskParameters"
  ): TypedContractMethod<
    [
      user: AddressLike,
      anomalyScore: BigNumberish,
      defaultProbability: BigNumberish,
      recoveryRate: BigNumberish,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "CreditAssessmentVerified"
  ): TypedContractEvent<
    CreditAssessmentVerifiedEvent.InputTuple,
    CreditAssessmentVerifiedEvent.OutputTuple,
    CreditAssessmentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "LoanProposalVerified"
  ): TypedContractEvent<
    LoanProposalVerifiedEvent.InputTuple,
    LoanProposalVerifiedEvent.OutputTuple,
    LoanProposalVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedSignerUpdated"
  ): TypedContractEvent<
    TrustedSignerUpdatedEvent.InputTuple,
    TrustedSignerUpdatedEvent.OutputTuple,
    TrustedSignerUpdatedEvent.OutputObject
  >;

  filters: {
    "CreditAssessmentVerified(address,uint256,string,uint256)": TypedContractEvent<
      CreditAssessmentVerifiedEvent.InputTuple,
      CreditAssessmentVerifiedEvent.OutputTuple,
      CreditAssessmentVerifiedEvent.OutputObject
    >;
    CreditAssessmentVerified: TypedContractEvent<
      CreditAssessmentVerifiedEvent.InputTuple,
      CreditAssessmentVerifiedEvent.OutputTuple,
      CreditAssessmentVerifiedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "LoanProposalVerified(address,uint256,uint256,uint256)": TypedContractEvent<
      LoanProposalVerifiedEvent.InputTuple,
      LoanProposalVerifiedEvent.OutputTuple,
      LoanProposalVerifiedEvent.OutputObject
    >;
    LoanProposalVerified: TypedContractEvent<
      LoanProposalVerifiedEvent.InputTuple,
      LoanProposalVerifiedEvent.OutputTuple,
      LoanProposalVerifiedEvent.OutputObject
    >;

    "TrustedSignerUpdated(address,address)": TypedContractEvent<
      TrustedSignerUpdatedEvent.InputTuple,
      TrustedSignerUpdatedEvent.OutputTuple,
      TrustedSignerUpdatedEvent.OutputObject
    >;
    TrustedSignerUpdated: TypedContractEvent<
      TrustedSignerUpdatedEvent.InputTuple,
      TrustedSignerUpdatedEvent.OutputTuple,
      TrustedSignerUpdatedEvent.OutputObject
    >;
  };
}
