/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ICollateralVault {
  export type CollateralStruct = {
    loanId: BytesLike;
    depositor: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    isLocked: boolean;
  };

  export type CollateralStructOutput = [
    loanId: string,
    depositor: string,
    token: string,
    amount: bigint,
    isLocked: boolean
  ] & {
    loanId: string;
    depositor: string;
    token: string;
    amount: bigint;
    isLocked: boolean;
  };
}

export interface ICollateralVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCollateral"
      | "getLockedAmount"
      | "getSupportedTokens"
      | "isTokenSupported"
      | "lockCollateral"
      | "seizeCollateral"
      | "unlockCollateral"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCollateral",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockedAmount",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCollateral",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seizeCollateral",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCollateral",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seizeCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCollateral",
    data: BytesLike
  ): Result;
}

export interface ICollateralVault extends BaseContract {
  connect(runner?: ContractRunner | null): ICollateralVault;
  waitForDeployment(): Promise<this>;

  interface: ICollateralVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCollateral: TypedContractMethod<
    [loanId: BytesLike],
    [ICollateralVault.CollateralStructOutput[]],
    "view"
  >;

  getLockedAmount: TypedContractMethod<
    [loanId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getSupportedTokens: TypedContractMethod<[], [string[]], "view">;

  isTokenSupported: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  lockCollateral: TypedContractMethod<
    [loanId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  seizeCollateral: TypedContractMethod<
    [loanId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockCollateral: TypedContractMethod<
    [loanId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCollateral"
  ): TypedContractMethod<
    [loanId: BytesLike],
    [ICollateralVault.CollateralStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLockedAmount"
  ): TypedContractMethod<
    [loanId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockCollateral"
  ): TypedContractMethod<
    [loanId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "seizeCollateral"
  ): TypedContractMethod<
    [loanId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockCollateral"
  ): TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;

  filters: {};
}
