/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CollateralVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "collaterals"
      | "getCollateralValue"
      | "loanCore"
      | "lockCollateral"
      | "lockCollateralFor"
      | "owner"
      | "renounceOwnership"
      | "setLoanCore"
      | "transferOwnership"
      | "unlockCollateral"
      | "userNonce"
      | "userTokenBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralLocked"
      | "CollateralUnlocked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "collaterals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollateralValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loanCore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockCollateral",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCollateralFor",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLoanCore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTokenBalance",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "collaterals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollateralValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanCore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateralFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLoanCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTokenBalance",
    data: BytesLike
  ): Result;
}

export namespace CollateralLockedEvent {
  export type InputTuple = [
    collateralId: BigNumberish,
    owner: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    loanId: BigNumberish
  ];
  export type OutputTuple = [
    collateralId: bigint,
    owner: string,
    token: string,
    amount: bigint,
    loanId: bigint
  ];
  export interface OutputObject {
    collateralId: bigint;
    owner: string;
    token: string;
    amount: bigint;
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralUnlockedEvent {
  export type InputTuple = [collateralId: BigNumberish];
  export type OutputTuple = [collateralId: bigint];
  export interface OutputObject {
    collateralId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CollateralVault extends BaseContract {
  connect(runner?: ContractRunner | null): CollateralVault;
  waitForDeployment(): Promise<this>;

  interface: CollateralVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  collaterals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        owner: string;
        token: string;
        amount: bigint;
        loanId: bigint;
        locked: boolean;
      }
    ],
    "view"
  >;

  getCollateralValue: TypedContractMethod<
    [collateralId: BigNumberish],
    [bigint],
    "view"
  >;

  loanCore: TypedContractMethod<[], [string], "view">;

  lockCollateral: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, loanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  lockCollateralFor: TypedContractMethod<
    [
      owner: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      loanId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLoanCore: TypedContractMethod<
    [_loanCore: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockCollateral: TypedContractMethod<
    [collateralId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userNonce: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userTokenBalance: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "collaterals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        owner: string;
        token: string;
        amount: bigint;
        loanId: bigint;
        locked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCollateralValue"
  ): TypedContractMethod<[collateralId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "loanCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockCollateral"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, loanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockCollateralFor"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      loanId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLoanCore"
  ): TypedContractMethod<[_loanCore: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockCollateral"
  ): TypedContractMethod<[collateralId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userNonce"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTokenBalance"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CollateralLocked"
  ): TypedContractEvent<
    CollateralLockedEvent.InputTuple,
    CollateralLockedEvent.OutputTuple,
    CollateralLockedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralUnlocked"
  ): TypedContractEvent<
    CollateralUnlockedEvent.InputTuple,
    CollateralUnlockedEvent.OutputTuple,
    CollateralUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CollateralLocked(uint256,address,address,uint256,uint256)": TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;
    CollateralLocked: TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;

    "CollateralUnlocked(uint256)": TypedContractEvent<
      CollateralUnlockedEvent.InputTuple,
      CollateralUnlockedEvent.OutputTuple,
      CollateralUnlockedEvent.OutputObject
    >;
    CollateralUnlocked: TypedContractEvent<
      CollateralUnlockedEvent.InputTuple,
      CollateralUnlockedEvent.OutputTuple,
      CollateralUnlockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
